### ISSUE TITLE
Flytt DokumentMetricsConfig.java

### ISSUE THREAD

**Issue by audun-persson** [navikt/dokumentfordeling#106]
Denne filen er plassert feil:
dokumentfordeling-integrations/dokfor-exposers/src/main/java/no/nav/dokumentfordeling/integrations/exposers/controllers/DokumentMetricsConfig.java

Bør heller ligge her:
dokumentfordeling-integrations/dokfor-shared/src/main/java/no/nav/dokumentfordeling/integrations/config/

**Comment by guruduttsverma** [comment]
Flyttet : pull request  : 
https://github.com/navikt/dokumentfordeling-integrations/pull/57

**Comment by guruduttsverma** [comment]
Done
